// Code generated by protoc-gen-gogo.
// source: unmarshal/test/test1.proto
// DO NOT EDIT!

/*
Package test is a generated protocol buffer package.

It is generated from these files:
	unmarshal/test/test1.proto

It has these top-level messages:
	Foo
	Bar
*/
package test

import proto "github.com/gogo/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type FooFoobar int32

const (
	Foo_e1 FooFoobar = 1
	Foo_e2 FooFoobar = 2
)

var FooFoobar_name = map[int32]string{
	1: "e1",
	2: "e2",
}
var FooFoobar_value = map[string]int32{
	"e1": 1,
	"e2": 2,
}

func (x FooFoobar) Enum() *FooFoobar {
	p := new(FooFoobar)
	*p = x
	return p
}
func (x FooFoobar) String() string {
	return proto.EnumName(FooFoobar_name, int32(x))
}
func (x *FooFoobar) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FooFoobar_value, data, "FooFoobar")
	if err != nil {
		return err
	}
	*x = FooFoobar(value)
	return nil
}

type Foo struct {
	F1               *string   `protobuf:"bytes,1,req,name=f1" json:"f1,omitempty"`
	F2               *int32    `protobuf:"varint,2,opt,name=f2" json:"f2,omitempty"`
	F3               *int64    `protobuf:"varint,3,opt,name=f3" json:"f3,omitempty"`
	F4               *uint32   `protobuf:"varint,4,opt,name=f4" json:"f4,omitempty"`
	F5               *uint64   `protobuf:"varint,5,opt,name=f5" json:"f5,omitempty"`
	F6               *int32    `protobuf:"zigzag32,6,opt,name=f6" json:"f6,omitempty"`
	F7               *bool     `protobuf:"varint,7,opt,name=f7" json:"f7,omitempty"`
	F8               *uint64   `protobuf:"fixed64,8,opt,name=f8" json:"f8,omitempty"`
	F9               *int64    `protobuf:"fixed64,9,opt,name=f9" json:"f9,omitempty"`
	F10              *float64  `protobuf:"fixed64,10,opt,name=f10" json:"f10,omitempty"`
	F11              []byte    `protobuf:"bytes,11,opt,name=f11" json:"f11,omitempty"`
	F12              *Bar      `protobuf:"bytes,12,opt,name=f12" json:"f12,omitempty"`
	F13              *uint32   `protobuf:"fixed32,13,opt,name=f13" json:"f13,omitempty"`
	F14              *int32    `protobuf:"fixed32,14,opt,name=f14" json:"f14,omitempty"`
	F15              *float32  `protobuf:"fixed32,15,opt,name=f15" json:"f15,omitempty"`
	F16              []*FooBaz `protobuf:"bytes,16,rep,name=f16" json:"f16,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Foo) Reset()         { *m = Foo{} }
func (m *Foo) String() string { return proto.CompactTextString(m) }
func (*Foo) ProtoMessage()    {}

func (m *Foo) GetF1() string {
	if m != nil && m.F1 != nil {
		return *m.F1
	}
	return ""
}

func (m *Foo) GetF2() int32 {
	if m != nil && m.F2 != nil {
		return *m.F2
	}
	return 0
}

func (m *Foo) GetF3() int64 {
	if m != nil && m.F3 != nil {
		return *m.F3
	}
	return 0
}

func (m *Foo) GetF4() uint32 {
	if m != nil && m.F4 != nil {
		return *m.F4
	}
	return 0
}

func (m *Foo) GetF5() uint64 {
	if m != nil && m.F5 != nil {
		return *m.F5
	}
	return 0
}

func (m *Foo) GetF6() int32 {
	if m != nil && m.F6 != nil {
		return *m.F6
	}
	return 0
}

func (m *Foo) GetF7() bool {
	if m != nil && m.F7 != nil {
		return *m.F7
	}
	return false
}

func (m *Foo) GetF8() uint64 {
	if m != nil && m.F8 != nil {
		return *m.F8
	}
	return 0
}

func (m *Foo) GetF9() int64 {
	if m != nil && m.F9 != nil {
		return *m.F9
	}
	return 0
}

func (m *Foo) GetF10() float64 {
	if m != nil && m.F10 != nil {
		return *m.F10
	}
	return 0
}

func (m *Foo) GetF11() []byte {
	if m != nil {
		return m.F11
	}
	return nil
}

func (m *Foo) GetF12() *Bar {
	if m != nil {
		return m.F12
	}
	return nil
}

func (m *Foo) GetF13() uint32 {
	if m != nil && m.F13 != nil {
		return *m.F13
	}
	return 0
}

func (m *Foo) GetF14() int32 {
	if m != nil && m.F14 != nil {
		return *m.F14
	}
	return 0
}

func (m *Foo) GetF15() float32 {
	if m != nil && m.F15 != nil {
		return *m.F15
	}
	return 0
}

func (m *Foo) GetF16() []*FooBaz {
	if m != nil {
		return m.F16
	}
	return nil
}

type FooBaz struct {
	F1               *string       `protobuf:"bytes,1,req,name=f1" json:"f1,omitempty"`
	F2               *FooFoobar    `protobuf:"varint,2,opt,name=f2,enum=test.FooFoobar" json:"f2,omitempty"`
	F3               *FooBazFoobaz `protobuf:"bytes,3,opt,name=f3" json:"f3,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *FooBaz) Reset()         { *m = FooBaz{} }
func (m *FooBaz) String() string { return proto.CompactTextString(m) }
func (*FooBaz) ProtoMessage()    {}

func (m *FooBaz) GetF1() string {
	if m != nil && m.F1 != nil {
		return *m.F1
	}
	return ""
}

func (m *FooBaz) GetF2() FooFoobar {
	if m != nil && m.F2 != nil {
		return *m.F2
	}
	return Foo_e1
}

func (m *FooBaz) GetF3() *FooBazFoobaz {
	if m != nil {
		return m.F3
	}
	return nil
}

type FooBazFoobaz struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FooBazFoobaz) Reset()         { *m = FooBazFoobaz{} }
func (m *FooBazFoobaz) String() string { return proto.CompactTextString(m) }
func (*FooBazFoobaz) ProtoMessage()    {}

func (m *FooBazFoobaz) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type Bar struct {
	Id               *int32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Bar) Reset()         { *m = Bar{} }
func (m *Bar) String() string { return proto.CompactTextString(m) }
func (*Bar) ProtoMessage()    {}

func (m *Bar) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func init() {
	proto.RegisterEnum("test.FooFoobar", FooFoobar_name, FooFoobar_value)
}
